In [45]:
import numpy as np
import scipy
from qiskit import QuantumCircuit
from qiskit.quantum_info import Operator

In [52]:
def t_mat(M: int):
    mat = 2*np.identity(M, dtype=int)
    for j in range(0,M-2+1):
        mat[j+1,j] = -1
        mat[j,j+1] = -1
    return mat

def u_inc(M: int):
    mat = np.zeros((M, M), dtype=int)
    for j in range(0,M-2+1):
        mat[j+1,j] = 1
    mat[0,M-1] = 1
    return mat

def proj_d(M: int):
    mat = np.zeros((M, M), dtype=int)
    for j in range(0,M-2+1):
        mat[j,j] = 1
    return mat

def s_hat(M: int):
    mat = np.zeros((M, M), dtype=int)
    for j in range(0,M-2+1):
        mat[j+1,j] = 1
    return mat

    

In [53]:
M = 4

u_inc(M)

array([[0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

Is $U_{inc}$ unitary?

In [54]:
norm_diff1 = np.linalg.norm( u_inc(M).dot(u_inc(M).T) - u_inc(M).T.dot(u_inc(M))) 
norm_diff2 = np.linalg.norm( u_inc(M).dot(u_inc(M).T) - np.identity(M)) 

np.isclose(norm_diff1,0) and np.isclose(norm_diff2,0)

np.True_

In [55]:
proj_d(M)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [56]:
s_hat(M)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [58]:
scipy.linalg.expm(-1j* 1* s_hat(M))

array([[ 1. +0.j        ,  0. +0.j        ,  0. +0.j        ,
         0. +0.j        ],
       [ 0. -1.j        ,  1. +0.j        ,  0. +0.j        ,
         0. +0.j        ],
       [-0.5+0.j        ,  0. -1.j        ,  1. +0.j        ,
         0. +0.j        ],
       [ 0. +0.16666667j, -0.5+0.j        ,  0. -1.j        ,
         1. +0.j        ]])

In [57]:
proj_d(M).dot(u_inc(M)).dot(proj_d(M))

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0]])

In [44]:
t_mat(4)

array([[ 2, -1,  0,  0],
       [-1,  2, -1,  0],
       [ 0, -1,  2, -1],
       [ 0,  0, -1,  2]])

In [49]:
t = 0.1
res = scipy.linalg.expm(-1j* t* t_mat(4))
res

array([[ 9.75174405e-01-1.97677638e-01j,  1.98007927e-02+9.76803770e-02j,
        -4.88809294e-03+9.90865494e-04j, -3.30619193e-05-1.63099569e-04j],
       [ 1.98007927e-02+9.76803770e-02j,  9.70286312e-01-1.96686773e-01j,
         1.97677308e-02+9.75172775e-02j, -4.88809294e-03+9.90865494e-04j],
       [-4.88809294e-03+9.90865494e-04j,  1.97677308e-02+9.75172775e-02j,
         9.70286312e-01-1.96686773e-01j,  1.98007927e-02+9.76803770e-02j],
       [-3.30619193e-05-1.63099569e-04j, -4.88809294e-03+9.90865494e-04j,
         1.98007927e-02+9.76803770e-02j,  9.75174405e-01-1.97677638e-01j]])

In [51]:
res.dot(res.conj().T)

array([[ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00-2.77555756e-17j,
        -3.46944695e-18+4.33680869e-19j,  0.00000000e+00+1.08420217e-19j],
       [ 0.00000000e+00+2.77555756e-17j,  1.00000000e+00+0.00000000e+00j,
         6.93889390e-18+2.77555756e-17j, -1.73472348e-18+0.00000000e+00j],
       [-3.46944695e-18-4.33680869e-19j,  6.93889390e-18-2.77555756e-17j,
         1.00000000e+00+0.00000000e+00j,  0.00000000e+00+4.16333634e-17j],
       [ 0.00000000e+00-1.08420217e-19j, -1.73472348e-18+0.00000000e+00j,
         0.00000000e+00-4.16333634e-17j,  1.00000000e+00+0.00000000e+00j]])